### ISSUE TITLE
Audio sometimes defaults to XAudio

### ISSUE THREAD

**Issue by Pobega** [flathub/com.fightcade.Fightcade#10]
Our build of Wine doesn't have XAudio support, so we should find some way to force `nAudSelect 0` in the fcade config.

If you're running into no sound use this to fix your configuration file: `sed -i "s/nAudSelect 1/nAudSelect 0/" ~/.var/app/com.fightcade.Fightcade/data/config/fcadefbneo/fcadefbneo.ini`

**Comment by VaGNaroK** [comment]
here is working version 2.0.86 of fightcade (there was an update on the emulators and after doing everything works normal and with audio), so for me so far it's working very well.

**Comment by Pobega** [comment]
Yeah. I am currently on vacation but need to take some time to look at what changed.

Final Burn used to ship with a default config ini that defaulted the audio to Direct Input. At first glance it seems that default ini is no longer shipped with the emulator and by it's own choice it defaults to XAudio2.

If you've already got a config from 2.0.82 you're probably fine but new installs will likely not have audio

**Comment by Pobega** [comment]
So just an update to this, this is still an issue but I haven't had a chance to look at it due to personal life.

https://github.com/Pobega/com.fightcade.Fightcade-ARCHIVE/issues/21

This is an old archived issue from my original repository, I'm linking it here so I don't lose it. Just in case this ever gets archived, here is the most pertinent comment:

> For future reference it looks like Valve builds Faudio:
>
> * https://github.com/flathub/com.valvesoftware.Steam/blob/6430f57c6cd005e14198d061c15d24e365f2a425/modules-32bit.yml#L42-L53
> * https://github.com/flathub/com.valvesoftware.Steam/blob/70d42305623a7afeab035f20b45a44b626bcaa3e/sources/FAudio-archive.json
>
> So it's entirely possible we can build FAudio ourselves as a dependency of Wine if it's decided we need XAudio support in the future.

So since Valve builds FAudio it's likely we can just copy this over and build wine32 with Faudio support, that way we don't have to worry about which audio selection FinalBurnNeo decides to pick.

**Comment by Pobega** [comment]
Resolved by https://github.com/flathub/com.fightcade.Fightcade/pull/22
