### ISSUE TITLE
Consider disabling WineDbg crashdialog

### ISSUE THREAD

**Issue by keenanweaver** [flathub/com.fightcade.Fightcade#102]
Usually always get a Wine crash dialog box when launching a game:

![winedbg](https://user-images.githubusercontent.com/37268985/198837065-afcd9d6a-3dbd-465c-87ff-5835a3bced6e.png)

To get rid of this, you just set a DWORD data "ShowCrashDialog" to a value of 0 in the prefix registry. Reference: https://unix.stackexchange.com/a/673529

![reg](https://user-images.githubusercontent.com/37268985/198837244-0dae4a11-e223-4c00-bc4c-753a3b2f3444.png)

Unsure if this is a good idea overall, as there may be function in having the pop up show, but I find it's mostly just a nuisance for Fightcade.

**Comment by Pobega** [comment]
Hum, that's interesting. Is there a good way to recreate this crash? I haven't seen a single crash like this on any of my systems, so I'm just a bit confused (and a little skeptical of a regedit suppressing what might be actual crashes.)

Do the exes launch normally after dismissing the crash message?

**Comment by keenanweaver** [comment]
I looked into it further. A reliable way to recreate the crash is using winecfg to alter settings for the prefix. I definitely have done this on my installations, but I used a winecfg outside of the provided Wine runtime for Fightcade, which probably screws it all up. Couldn't seem to figure out how to run winecfg from the Fightcade Wine runtime.

Really, the only thing wrong as far as I can tell is just the pop-up box. Haven't experienced any sort of problem launching, playing, etc. However, this is absolutely not an issue with the Flatpak as I removed everything just now and started fresh with no problems. It's a PEBCAK.

**Comment by Pobega** [comment]
You should be able to update the wine prefix using the Wine from within the Flatpak using `flatpak run --env=WINEPREFIX=/var/data/winepfx /app/wine/bin/winecfg`, though this is off the top of my head so it could be wrong (not sure if `flatpak run` respects `--env` like `flatpak override` does?)

Generally the Flatpak tracks a pretty old version of Wine based on what is recommended by Fightcade (currently Wine 5.0.3) so modifying it with your host's wine could definitely cause issues. But that version recommendation hasn't been updated in a while so `beta` is currently testing Wine 7.0, not that that resolves the issue here.

Winecfg could be exposed via a `.desktop` file (named something like `Fightcade winecfg` probably,) I'm not opposed to including one if it's something you find generally useful.

**Comment by keenanweaver** [comment]
I could see it being useful for some, but it's probably not necessary. Not sure what other users would want to do in winecfg. The only reason I use winecfg is to change the default theme from ancient Windows 95 to a modern-looking theme and set a larger font size.

![wine](https://user-images.githubusercontent.com/37268985/198853721-5b32ffe1-eab2-4148-a417-625244558d2f.png)

Got it working with your guidance. Here's how I launched winecfg:
`flatpak ps | grep Fightcade` (there will be two processes, try entering both.)
`flatpak enter XXXXX bash` (XXXXX is the PID)
`WINEPREFIX=/var/data/winepfx /app/wine/bin/winecfg`

Thanks for the support!

**Comment by Pobega** [comment]
I wonder if it makes sense to do some of these modifications to the wine config by default, honestly. I hate making decisions for users, but the default wine setup is what I'd call "just okay".

Is there an easily scriptable way to set these config options (the theme and fonts)? I could always put some logic in the wrapper script that if the wine prefix folder is empty we apply these changes after initially creating the prefix.

**Comment by keenanweaver** [comment]
It's [easy enough](https://askubuntu.com/a/956473) to import it as a reg file with regedit.  `wine start regedit.exe /home/myname/path/foo.reg`

Here's an example adapted from [this theme](https://www.linux-apps.com/p/1259774/).
![theme](https://user-images.githubusercontent.com/37268985/199070307-5bca9519-d097-4b8a-8b68-9bbdb610e933.png)
[wine_breeze_colors.txt](https://github.com/flathub/com.fightcade.Fightcade/files/9903419/wine_breeze_colors.txt)

Once Fightcade says newer Wine versions are good, it might be better to just use the official 'Light' theme (or 'Dark' if they make one). Not sure how to programmaticaly set that, but I think in new Wine builds, it's set automatically. Here's how that looks:

![winetheme](https://user-images.githubusercontent.com/37268985/199070956-17f5adaa-3cc7-4528-9749-2fce5ff1206e.png)
