### ISSUE TITLE
may you please update fightcade

### ISSUE THREAD

**Issue by helpme631** [flathub/com.fightcade.Fightcade#16]
its outdated

**Comment by Pobega** [comment]
The Flatpak lags a few hours behind upstream and needs to be manually merged; see https://github.com/flathub/com.fightcade.Fightcade/pull/17

**Comment by Pobega** [comment]
By the way, in the future feel free to ping me on the #linux-version channel on the Fightcade Discord if you're in there if there's a dangling pull request open.

**Comment by bilelmoussaoui** [comment]
@Pobega you can enable auto-merge for the bot by the way :) it will only merge the PR if the build was successful

**Comment by Pobega** [comment]
@bilelmoussaoui How do I go about setting it up to do that? I don't see it on https://github.com/flathub/flathub/wiki/App-Maintenance

**Comment by bilelmoussaoui** [comment]
@Pobega by adding `"automerge-flathubbot-prs": true` to flathub.json

**Comment by Pobega** [comment]
Thanks, that's really helpful

**Comment by Pobega** [comment]
@bilelmoussaoui Just a consideration that maybe that should be added to the `App Maintenance` page (or the Wiki in general, I couldn't find it in a quick search). I noticed very few Flathub applications use it (I searched the org and got `8` results)
