### ISSUE TITLE
Configure control.

### ISSUE THREAD

**Issue by VaGNaroK** [flathub/com.fightcade.Fightcade#4]
every time i go to play with someone i have to open the control options and map again to play, after leaving and entering another fight i have to redo the process, is anyone else having this problem?

**Comment by Pobega** [comment]
Do you know where the emulator is meant to store the config bindings in a normal install of Fightcade?

I've confirmed this on my end, it's likely that I need to just give FBNeo a file to write to.

**Comment by Pobega** [comment]
I'm merging https://github.com/flathub/com.fightcade.Fightcade/pull/5 into the beta branch which fixes this issue. Feel free to re-open this if that doesn't resolve it for you.

Thanks!
