### ISSUE TITLE
cant open flycast 

### ISSUE THREAD

**Issue by torao2** [flathub/com.fightcade.Fightcade#91]
Hello, so i tried to run various games in test game offline in fightcade (akatsuki blitskampf, ready2rumble round 1), doesnt boot up,tried deleting emu.cfg didnt do anything.

**Comment by Pobega** [comment]
The issue stems from https://github.com/blueminder/flycast-dojo/commit/90ad0d5570eb04858a3c41f2a69c58c43de1ba89

Flycast Dojo was changed to build against Ubuntu 22.04. It seems as a side effect of that change a chunk of the dynamically linked libraries were updated to versions not currently available in the Freedesktop runtime (most importantly OpenSSL 3.) I don't expect them to be available until Freedesktop runtime `22.08` is released.

Here's `ldd` output from an old (working) install of Flycast and the new (broken) version:
Old: 
```
    libzip.so.5 => /app/lib/libzip.so.5 (0x00007f0a9f4c3000)
    libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f0a9f42c000)
    libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f0a9f148000)
```
New:
```
    libzip.so.4 => not found
    libssl.so.3 => not found
    libcrypto.so.3 => not found
```

**Comment by Pobega** [comment]
There are two options here:

1. Build SSL/Crypto libraries manually until Freedesktop `22.08` is available.
2. Roll back Flycast to `ubuntu-latest` in the Github Ci until `22.08` is available.

After speaking to blueminder in Discord I'm going to take a quick stab at option **#1** tonight, but blueminder and pof are OK to push a Fightcade update with Flycast Dojo built against the older Ubuntu tomorrow.

I'll document here with any progress I make on trying to get the new Flycast to work.

**Comment by Pobega** [comment]
Closing this due to #92 

> Flycast Dojo 0.4.55
> - Linux: Revert to Ubuntu 20.04 environment (fixes Flatpak and 20.04 compatibility)

**Comment by man-of-eel** [comment]
I just installed Fightcade today, but i still have this issue? With libzip.so.4 not being found.

**Comment by Pobega** [comment]
Yep, this is unsurprising. Flycast is going to be broken, I wasn't made aware this update was coming down the pipeline.

**Comment by Pobega** [comment]
@man-of-eel could you please try this test version and let me know if it resolves the issue for you? Won't be able to look at it for a few hours and I'd like to ship this sooner rather than later. https://github.com/flathub/com.fightcade.Fightcade/pull/110#issuecomment-1359998835

**Comment by man-of-eel** [comment]
Gives me a different error... weird
```
$ xdg-open fcade://play/flycast/azumanga
$ bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```
Could it be because i installed it on a different installation?

**Comment by Pobega** [comment]
Can you try just launching Flycast directly from the Flatpak? `flatpak run --command=sh com.fightcade.Fightcade//test` should get you a shell, then you can `cd` into `/app/Fightcade/fightcade/flycast` and run `./flycast.elf` manually to see if it launches.

It's possible having two versions installed simultaneously is causing strange errors, this will test that Flycast itself works as expected (and if it launches I can merge after upgrading `com.fightcade.Fightcade.Wine`)

**Comment by man-of-eel** [comment]
`flatpak run --command=sh com.fightcade.Fightcade//test` gives me the same error, even after uninstalling the stable version.

**Comment by Pobega** [comment]
@man-of-eel could you try the most recent build (here: https://github.com/flathub/com.fightcade.Fightcade/pull/110#issuecomment-1360425294) and let me know if it works?

**Comment by Pobega** [comment]
I just merged the changes thanks to @torao2 doing some testing for me on the Discord. If you continue to have issues related to the Flycast changes feel free to re-open this.
