### ISSUE TITLE
Missing emulator folder

### ISSUE THREAD

**Issue by luni3359** [flathub/com.fightcade.Fightcade#94]
I can't find the emulator folder, I've been trying to set up automatic rom downloads as seen on this guide:
https://fightcade.guide/
> 1. Download the JSON pack from [this link](https://fightcade.download/fc2json.zip) [Updated 21 Jun 2022]
> 2. Extract the zip archive into the emulator folder that is inside the folder in which you installed Fightcade

I tried placing the files mentioned there under the following directories because they seemed similar but neither worked.
```
~/.var/app/com.fightcade.Fightcade/data/config/
~/.var/app/com.fightcade.Fightcade/data/ROMs/
```
Have you guys managed to set it up correctly?

**Comment by Pobega** [comment]
Did you look at the README? 

https://github.com/flathub/com.fightcade.Fightcade#how-do-i-use-fightcade-json

**Comment by luni3359** [comment]
Damn I'm dumb, I completely glanced over that part. The games I tried worked properly. Sorry and thanks for the help!
